[workspace]
members = ["gru-vulkan-derive"]

[package]
name = "gru-vulkan"
version = "0.1.0"
authors = ["Jannik Fehre"]
edition = "2021"

[features]
math = ["gru-misc/math"]

[dependencies]
gru-vulkan-derive = { path = "gru-vulkan-derive" }
ash = "0.33.0"
ash-window = "0.7.0"
raw-window-handle = "0.3.3"
inline-spirv = "0.1.2"
vk-mem = { git = "https://github.com/aclysma/vk-mem-rs.git", branch = "ash-0.33-build-fix" }
gru-misc = { path = "../gru-misc", optional = true }
serde = { version = "1.0.129", default-features = false, features = ["derive"], optional = true }
