[package]
name = "gru-vulkan-derive"
version = "0.1.0"
authors = ["Jannik Fehre"]
license = "MIT"
edition = "2021"

[dependencies]
syn = "2.0.79"
quote = "1.0.37"
proc-macro2 = "1.0.86"

[lib]
proc-macro = true
