[package]
name = "gru-vulkan-derive"
version = "0.1.0"
authors = ["Jannik Fehre"]
edition = "2018"

[dependencies]
syn = { version = "1.0.70" }
quote = "1.0.9"
proc-macro2 = "1.0.26"

[lib]
proc-macro = true
